### PR TITLE
#9 Remove categories if they appear in pin's content.

### PR DESCRIPTION
**Pull request by p16i**
Related to #9, I mainly tested with unit-test and haven't tested with real data yet. It would be nice if you can point me out how to do so.

To run the unit-test

```
# Install deps
> npm install mocha -g && npm install

# Run the test
> mocha test/utils.spec.js
```

### CODE REVIEW

**Comment by rapee** [comment]
Looks good to me! Thanks @heytitle

**Comment by rapee** [comment]
Close #9

**Comment by rapee** [comment]
Oh I meant to merge. Reopen to merge.

**Comment by p16i** [comment]
@rapee  you're welcome 🍻

**Pull request merged**
